png("plot4.png")
par(mfrow=c(2,2))
plot(subset_hec$DateTimePosixct,subset_hec$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(subset_hec$DateTimePosixct,subset_hec$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(subset_hec$DateTimePosixct, subset_hec$Sub_metering_1 ,type="l", ylim=c(0,30), xlab="", ylab = "Energy sub metering")
lines(subset_hec$DateTimePosixct, subset_hec$Sub_metering_2 , col= "red", type="l")
lines(subset_hec$DateTimePosixct, subset_hec$Sub_metering_3 , col= "blue", type="l")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), lwd=c(1,1,1), bty="n", cex=0.5)
plot(subset_hec$DateTimePosixct,subset_hec$Global_reactive_power, type="l", xlab="datetime", ylab="Global_Reactive_Power (kilowatts)")
dev.off()